// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: connector/v2/destination.proto

package connectorv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DestinationPlugin_Configure_FullMethodName          = "/connector.v2.DestinationPlugin/Configure"
	DestinationPlugin_Open_FullMethodName               = "/connector.v2.DestinationPlugin/Open"
	DestinationPlugin_Run_FullMethodName                = "/connector.v2.DestinationPlugin/Run"
	DestinationPlugin_Stop_FullMethodName               = "/connector.v2.DestinationPlugin/Stop"
	DestinationPlugin_Teardown_FullMethodName           = "/connector.v2.DestinationPlugin/Teardown"
	DestinationPlugin_LifecycleOnCreated_FullMethodName = "/connector.v2.DestinationPlugin/LifecycleOnCreated"
	DestinationPlugin_LifecycleOnUpdated_FullMethodName = "/connector.v2.DestinationPlugin/LifecycleOnUpdated"
	DestinationPlugin_LifecycleOnDeleted_FullMethodName = "/connector.v2.DestinationPlugin/LifecycleOnDeleted"
)

// DestinationPluginClient is the client API for DestinationPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DestinationPluginClient interface {
	// Configure is the first function to be called in a plugin. It provides the
	// plugin with the configuration that needs to be validated and stored. In
	// case the configuration is not valid it should return an error status.
	Configure(ctx context.Context, in *Destination_Configure_Request, opts ...grpc.CallOption) (*Destination_Configure_Response, error)
	// Open is called after Configure to signal the plugin it can prepare to
	// start writing records. If needed, the plugin should open connections in
	// this function.
	Open(ctx context.Context, in *Destination_Open_Request, opts ...grpc.CallOption) (*Destination_Open_Response, error)
	// Run will open a bidirectional stream between Conduit and the plugin.
	// Conduit will be streaming records to the plugin that should be written
	// to the 3rd party resource. The plugin is responsible for sending
	// acknowledgments back to Conduit once a record has been processed. The
	// acknowledgment should contain an error in case a record could not be
	// successfully processed. The stream should still stay open in case Conduit
	// is able to recover from the error and the pipeline keeps running.
	Run(ctx context.Context, opts ...grpc.CallOption) (DestinationPlugin_RunClient, error)
	// Stop signals to the plugin that the record with the specified position is
	// the last one and no more records will be written to the stream after it.
	// Once the plugin receives the last record it should flush any records that
	// might be cached and not yet written to the 3rd party resource.
	Stop(ctx context.Context, in *Destination_Stop_Request, opts ...grpc.CallOption) (*Destination_Stop_Response, error)
	// Teardown signals to the plugin that there will be no more calls to any
	// other function. After Teardown returns, the plugin should be ready for a
	// graceful shutdown.
	Teardown(ctx context.Context, in *Destination_Teardown_Request, opts ...grpc.CallOption) (*Destination_Teardown_Response, error)
	// LifecycleOnCreated is called after Configure and before Open when the
	// connector is run for the first time. This call will be skipped if a
	// connector was already started before. This method can be used to do some
	// initialization that needs to happen only once in the lifetime of a
	// connector (e.g. create a bucket). Anything that the connector creates in
	// this method is considered to be owned by this connector and should be
	// cleaned up in LifecycleOnDeleted.
	LifecycleOnCreated(ctx context.Context, in *Destination_Lifecycle_OnCreated_Request, opts ...grpc.CallOption) (*Destination_Lifecycle_OnCreated_Response, error)
	// LifecycleOnUpdated is called after Configure and before Open when the
	// connector configuration has changed since the last run. This call will be
	// skipped if the connector configuration did not change. It can be used to
	// update anything that was initialized in LifecycleOnCreated, in case the
	// configuration change affects it.
	LifecycleOnUpdated(ctx context.Context, in *Destination_Lifecycle_OnUpdated_Request, opts ...grpc.CallOption) (*Destination_Lifecycle_OnUpdated_Response, error)
	// LifecycleOnDeleted is called when the connector was deleted. It will be the
	// only method that is called in that case. This method can be used to clean
	// up anything that was initialized in LifecycleOnCreated.
	LifecycleOnDeleted(ctx context.Context, in *Destination_Lifecycle_OnDeleted_Request, opts ...grpc.CallOption) (*Destination_Lifecycle_OnDeleted_Response, error)
}

type destinationPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDestinationPluginClient(cc grpc.ClientConnInterface) DestinationPluginClient {
	return &destinationPluginClient{cc}
}

func (c *destinationPluginClient) Configure(ctx context.Context, in *Destination_Configure_Request, opts ...grpc.CallOption) (*Destination_Configure_Response, error) {
	out := new(Destination_Configure_Response)
	err := c.cc.Invoke(ctx, DestinationPlugin_Configure_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationPluginClient) Open(ctx context.Context, in *Destination_Open_Request, opts ...grpc.CallOption) (*Destination_Open_Response, error) {
	out := new(Destination_Open_Response)
	err := c.cc.Invoke(ctx, DestinationPlugin_Open_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationPluginClient) Run(ctx context.Context, opts ...grpc.CallOption) (DestinationPlugin_RunClient, error) {
	stream, err := c.cc.NewStream(ctx, &DestinationPlugin_ServiceDesc.Streams[0], DestinationPlugin_Run_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &destinationPluginRunClient{stream}
	return x, nil
}

type DestinationPlugin_RunClient interface {
	Send(*Destination_Run_Request) error
	Recv() (*Destination_Run_Response, error)
	grpc.ClientStream
}

type destinationPluginRunClient struct {
	grpc.ClientStream
}

func (x *destinationPluginRunClient) Send(m *Destination_Run_Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *destinationPluginRunClient) Recv() (*Destination_Run_Response, error) {
	m := new(Destination_Run_Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *destinationPluginClient) Stop(ctx context.Context, in *Destination_Stop_Request, opts ...grpc.CallOption) (*Destination_Stop_Response, error) {
	out := new(Destination_Stop_Response)
	err := c.cc.Invoke(ctx, DestinationPlugin_Stop_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationPluginClient) Teardown(ctx context.Context, in *Destination_Teardown_Request, opts ...grpc.CallOption) (*Destination_Teardown_Response, error) {
	out := new(Destination_Teardown_Response)
	err := c.cc.Invoke(ctx, DestinationPlugin_Teardown_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationPluginClient) LifecycleOnCreated(ctx context.Context, in *Destination_Lifecycle_OnCreated_Request, opts ...grpc.CallOption) (*Destination_Lifecycle_OnCreated_Response, error) {
	out := new(Destination_Lifecycle_OnCreated_Response)
	err := c.cc.Invoke(ctx, DestinationPlugin_LifecycleOnCreated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationPluginClient) LifecycleOnUpdated(ctx context.Context, in *Destination_Lifecycle_OnUpdated_Request, opts ...grpc.CallOption) (*Destination_Lifecycle_OnUpdated_Response, error) {
	out := new(Destination_Lifecycle_OnUpdated_Response)
	err := c.cc.Invoke(ctx, DestinationPlugin_LifecycleOnUpdated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *destinationPluginClient) LifecycleOnDeleted(ctx context.Context, in *Destination_Lifecycle_OnDeleted_Request, opts ...grpc.CallOption) (*Destination_Lifecycle_OnDeleted_Response, error) {
	out := new(Destination_Lifecycle_OnDeleted_Response)
	err := c.cc.Invoke(ctx, DestinationPlugin_LifecycleOnDeleted_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DestinationPluginServer is the server API for DestinationPlugin service.
// All implementations must embed UnimplementedDestinationPluginServer
// for forward compatibility
type DestinationPluginServer interface {
	// Configure is the first function to be called in a plugin. It provides the
	// plugin with the configuration that needs to be validated and stored. In
	// case the configuration is not valid it should return an error status.
	Configure(context.Context, *Destination_Configure_Request) (*Destination_Configure_Response, error)
	// Open is called after Configure to signal the plugin it can prepare to
	// start writing records. If needed, the plugin should open connections in
	// this function.
	Open(context.Context, *Destination_Open_Request) (*Destination_Open_Response, error)
	// Run will open a bidirectional stream between Conduit and the plugin.
	// Conduit will be streaming records to the plugin that should be written
	// to the 3rd party resource. The plugin is responsible for sending
	// acknowledgments back to Conduit once a record has been processed. The
	// acknowledgment should contain an error in case a record could not be
	// successfully processed. The stream should still stay open in case Conduit
	// is able to recover from the error and the pipeline keeps running.
	Run(DestinationPlugin_RunServer) error
	// Stop signals to the plugin that the record with the specified position is
	// the last one and no more records will be written to the stream after it.
	// Once the plugin receives the last record it should flush any records that
	// might be cached and not yet written to the 3rd party resource.
	Stop(context.Context, *Destination_Stop_Request) (*Destination_Stop_Response, error)
	// Teardown signals to the plugin that there will be no more calls to any
	// other function. After Teardown returns, the plugin should be ready for a
	// graceful shutdown.
	Teardown(context.Context, *Destination_Teardown_Request) (*Destination_Teardown_Response, error)
	// LifecycleOnCreated is called after Configure and before Open when the
	// connector is run for the first time. This call will be skipped if a
	// connector was already started before. This method can be used to do some
	// initialization that needs to happen only once in the lifetime of a
	// connector (e.g. create a bucket). Anything that the connector creates in
	// this method is considered to be owned by this connector and should be
	// cleaned up in LifecycleOnDeleted.
	LifecycleOnCreated(context.Context, *Destination_Lifecycle_OnCreated_Request) (*Destination_Lifecycle_OnCreated_Response, error)
	// LifecycleOnUpdated is called after Configure and before Open when the
	// connector configuration has changed since the last run. This call will be
	// skipped if the connector configuration did not change. It can be used to
	// update anything that was initialized in LifecycleOnCreated, in case the
	// configuration change affects it.
	LifecycleOnUpdated(context.Context, *Destination_Lifecycle_OnUpdated_Request) (*Destination_Lifecycle_OnUpdated_Response, error)
	// LifecycleOnDeleted is called when the connector was deleted. It will be the
	// only method that is called in that case. This method can be used to clean
	// up anything that was initialized in LifecycleOnCreated.
	LifecycleOnDeleted(context.Context, *Destination_Lifecycle_OnDeleted_Request) (*Destination_Lifecycle_OnDeleted_Response, error)
	mustEmbedUnimplementedDestinationPluginServer()
}

// UnimplementedDestinationPluginServer must be embedded to have forward compatible implementations.
type UnimplementedDestinationPluginServer struct {
}

func (UnimplementedDestinationPluginServer) Configure(context.Context, *Destination_Configure_Request) (*Destination_Configure_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedDestinationPluginServer) Open(context.Context, *Destination_Open_Request) (*Destination_Open_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedDestinationPluginServer) Run(DestinationPlugin_RunServer) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedDestinationPluginServer) Stop(context.Context, *Destination_Stop_Request) (*Destination_Stop_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedDestinationPluginServer) Teardown(context.Context, *Destination_Teardown_Request) (*Destination_Teardown_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Teardown not implemented")
}
func (UnimplementedDestinationPluginServer) LifecycleOnCreated(context.Context, *Destination_Lifecycle_OnCreated_Request) (*Destination_Lifecycle_OnCreated_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LifecycleOnCreated not implemented")
}
func (UnimplementedDestinationPluginServer) LifecycleOnUpdated(context.Context, *Destination_Lifecycle_OnUpdated_Request) (*Destination_Lifecycle_OnUpdated_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LifecycleOnUpdated not implemented")
}
func (UnimplementedDestinationPluginServer) LifecycleOnDeleted(context.Context, *Destination_Lifecycle_OnDeleted_Request) (*Destination_Lifecycle_OnDeleted_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LifecycleOnDeleted not implemented")
}
func (UnimplementedDestinationPluginServer) mustEmbedUnimplementedDestinationPluginServer() {}

// UnsafeDestinationPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DestinationPluginServer will
// result in compilation errors.
type UnsafeDestinationPluginServer interface {
	mustEmbedUnimplementedDestinationPluginServer()
}

func RegisterDestinationPluginServer(s grpc.ServiceRegistrar, srv DestinationPluginServer) {
	s.RegisterService(&DestinationPlugin_ServiceDesc, srv)
}

func _DestinationPlugin_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Destination_Configure_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationPluginServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationPlugin_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationPluginServer).Configure(ctx, req.(*Destination_Configure_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationPlugin_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Destination_Open_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationPluginServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationPlugin_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationPluginServer).Open(ctx, req.(*Destination_Open_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationPlugin_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DestinationPluginServer).Run(&destinationPluginRunServer{stream})
}

type DestinationPlugin_RunServer interface {
	Send(*Destination_Run_Response) error
	Recv() (*Destination_Run_Request, error)
	grpc.ServerStream
}

type destinationPluginRunServer struct {
	grpc.ServerStream
}

func (x *destinationPluginRunServer) Send(m *Destination_Run_Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *destinationPluginRunServer) Recv() (*Destination_Run_Request, error) {
	m := new(Destination_Run_Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _DestinationPlugin_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Destination_Stop_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationPluginServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationPlugin_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationPluginServer).Stop(ctx, req.(*Destination_Stop_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationPlugin_Teardown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Destination_Teardown_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationPluginServer).Teardown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationPlugin_Teardown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationPluginServer).Teardown(ctx, req.(*Destination_Teardown_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationPlugin_LifecycleOnCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Destination_Lifecycle_OnCreated_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationPluginServer).LifecycleOnCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationPlugin_LifecycleOnCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationPluginServer).LifecycleOnCreated(ctx, req.(*Destination_Lifecycle_OnCreated_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationPlugin_LifecycleOnUpdated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Destination_Lifecycle_OnUpdated_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationPluginServer).LifecycleOnUpdated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationPlugin_LifecycleOnUpdated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationPluginServer).LifecycleOnUpdated(ctx, req.(*Destination_Lifecycle_OnUpdated_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _DestinationPlugin_LifecycleOnDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Destination_Lifecycle_OnDeleted_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DestinationPluginServer).LifecycleOnDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DestinationPlugin_LifecycleOnDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DestinationPluginServer).LifecycleOnDeleted(ctx, req.(*Destination_Lifecycle_OnDeleted_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// DestinationPlugin_ServiceDesc is the grpc.ServiceDesc for DestinationPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DestinationPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connector.v2.DestinationPlugin",
	HandlerType: (*DestinationPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Configure",
			Handler:    _DestinationPlugin_Configure_Handler,
		},
		{
			MethodName: "Open",
			Handler:    _DestinationPlugin_Open_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _DestinationPlugin_Stop_Handler,
		},
		{
			MethodName: "Teardown",
			Handler:    _DestinationPlugin_Teardown_Handler,
		},
		{
			MethodName: "LifecycleOnCreated",
			Handler:    _DestinationPlugin_LifecycleOnCreated_Handler,
		},
		{
			MethodName: "LifecycleOnUpdated",
			Handler:    _DestinationPlugin_LifecycleOnUpdated_Handler,
		},
		{
			MethodName: "LifecycleOnDeleted",
			Handler:    _DestinationPlugin_LifecycleOnDeleted_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _DestinationPlugin_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connector/v2/destination.proto",
}
