// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: connector/v2/destination.proto

package connectorv2

import (
	v1 "github.com/conduitio/conduit-commons/proto/opencdc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Destination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination) Reset() {
	*x = Destination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination) ProtoMessage() {}

func (x *Destination) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination.ProtoReflect.Descriptor instead.
func (*Destination) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0}
}

type Destination_Configure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Configure) Reset() {
	*x = Destination_Configure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Configure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Configure) ProtoMessage() {}

func (x *Destination_Configure) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Configure.ProtoReflect.Descriptor instead.
func (*Destination_Configure) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 0}
}

type Destination_Open struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Open) Reset() {
	*x = Destination_Open{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Open) ProtoMessage() {}

func (x *Destination_Open) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Open.ProtoReflect.Descriptor instead.
func (*Destination_Open) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 1}
}

type Destination_Run struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Run) Reset() {
	*x = Destination_Run{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Run) ProtoMessage() {}

func (x *Destination_Run) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Run.ProtoReflect.Descriptor instead.
func (*Destination_Run) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 2}
}

type Destination_Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Stop) Reset() {
	*x = Destination_Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Stop) ProtoMessage() {}

func (x *Destination_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Stop.ProtoReflect.Descriptor instead.
func (*Destination_Stop) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 3}
}

type Destination_Teardown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Teardown) Reset() {
	*x = Destination_Teardown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Teardown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Teardown) ProtoMessage() {}

func (x *Destination_Teardown) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Teardown.ProtoReflect.Descriptor instead.
func (*Destination_Teardown) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 4}
}

type Destination_Lifecycle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Lifecycle) Reset() {
	*x = Destination_Lifecycle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle) ProtoMessage() {}

func (x *Destination_Lifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5}
}

type Destination_Configure_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Config contains the raw plugin settings.
	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Destination_Configure_Request) Reset() {
	*x = Destination_Configure_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Configure_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Configure_Request) ProtoMessage() {}

func (x *Destination_Configure_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Configure_Request.ProtoReflect.Descriptor instead.
func (*Destination_Configure_Request) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Destination_Configure_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Destination_Configure_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Configure_Response) Reset() {
	*x = Destination_Configure_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Configure_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Configure_Response) ProtoMessage() {}

func (x *Destination_Configure_Response) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Configure_Response.ProtoReflect.Descriptor instead.
func (*Destination_Configure_Response) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 0, 1}
}

type Destination_Open_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Open_Request) Reset() {
	*x = Destination_Open_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Open_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Open_Request) ProtoMessage() {}

func (x *Destination_Open_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Open_Request.ProtoReflect.Descriptor instead.
func (*Destination_Open_Request) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 1, 0}
}

type Destination_Open_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Open_Response) Reset() {
	*x = Destination_Open_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Open_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Open_Response) ProtoMessage() {}

func (x *Destination_Open_Response) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Open_Response.ProtoReflect.Descriptor instead.
func (*Destination_Open_Response) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 1, 1}
}

type Destination_Run_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Records contains a batch of OpenCDC records that should be written to
	// the 3rd party resource.
	Records []*v1.Record `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
}

func (x *Destination_Run_Request) Reset() {
	*x = Destination_Run_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Run_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Run_Request) ProtoMessage() {}

func (x *Destination_Run_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Run_Request.ProtoReflect.Descriptor instead.
func (*Destination_Run_Request) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Destination_Run_Request) GetRecords() []*v1.Record {
	if x != nil {
		return x.Records
	}
	return nil
}

type Destination_Run_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Ack contains the acknowledgments for the records that were processed.
	Acks []*Destination_Run_Response_Ack `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
}

func (x *Destination_Run_Response) Reset() {
	*x = Destination_Run_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Run_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Run_Response) ProtoMessage() {}

func (x *Destination_Run_Response) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Run_Response.ProtoReflect.Descriptor instead.
func (*Destination_Run_Response) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Destination_Run_Response) GetAcks() []*Destination_Run_Response_Ack {
	if x != nil {
		return x.Acks
	}
	return nil
}

type Destination_Run_Response_Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// These is the position of the record that was processed.
	Position []byte `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	// Error should be empty if the record was successfully processed or
	// should contain a descriptive message in case the record
	// processing failed.
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Destination_Run_Response_Ack) Reset() {
	*x = Destination_Run_Response_Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Run_Response_Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Run_Response_Ack) ProtoMessage() {}

func (x *Destination_Run_Response_Ack) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Run_Response_Ack.ProtoReflect.Descriptor instead.
func (*Destination_Run_Response_Ack) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 2, 1, 0}
}

func (x *Destination_Run_Response_Ack) GetPosition() []byte {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Destination_Run_Response_Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Destination_Stop_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This is the position of the last record that was sent into the stream.
	// Conduit won't send any records after a record with this position is
	// received.
	LastPosition []byte `protobuf:"bytes,1,opt,name=last_position,json=lastPosition,proto3" json:"last_position,omitempty"`
}

func (x *Destination_Stop_Request) Reset() {
	*x = Destination_Stop_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Stop_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Stop_Request) ProtoMessage() {}

func (x *Destination_Stop_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Stop_Request.ProtoReflect.Descriptor instead.
func (*Destination_Stop_Request) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Destination_Stop_Request) GetLastPosition() []byte {
	if x != nil {
		return x.LastPosition
	}
	return nil
}

type Destination_Stop_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Stop_Response) Reset() {
	*x = Destination_Stop_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Stop_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Stop_Response) ProtoMessage() {}

func (x *Destination_Stop_Response) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Stop_Response.ProtoReflect.Descriptor instead.
func (*Destination_Stop_Response) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 3, 1}
}

type Destination_Teardown_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Teardown_Request) Reset() {
	*x = Destination_Teardown_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Teardown_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Teardown_Request) ProtoMessage() {}

func (x *Destination_Teardown_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Teardown_Request.ProtoReflect.Descriptor instead.
func (*Destination_Teardown_Request) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 4, 0}
}

type Destination_Teardown_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Teardown_Response) Reset() {
	*x = Destination_Teardown_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Teardown_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Teardown_Response) ProtoMessage() {}

func (x *Destination_Teardown_Response) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Teardown_Response.ProtoReflect.Descriptor instead.
func (*Destination_Teardown_Response) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 4, 1}
}

type Destination_Lifecycle_OnCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Lifecycle_OnCreated) Reset() {
	*x = Destination_Lifecycle_OnCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle_OnCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle_OnCreated) ProtoMessage() {}

func (x *Destination_Lifecycle_OnCreated) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle_OnCreated.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle_OnCreated) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5, 0}
}

type Destination_Lifecycle_OnUpdated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Lifecycle_OnUpdated) Reset() {
	*x = Destination_Lifecycle_OnUpdated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle_OnUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle_OnUpdated) ProtoMessage() {}

func (x *Destination_Lifecycle_OnUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle_OnUpdated.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle_OnUpdated) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5, 1}
}

type Destination_Lifecycle_OnDeleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Lifecycle_OnDeleted) Reset() {
	*x = Destination_Lifecycle_OnDeleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle_OnDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle_OnDeleted) ProtoMessage() {}

func (x *Destination_Lifecycle_OnDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle_OnDeleted.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle_OnDeleted) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5, 2}
}

type Destination_Lifecycle_OnCreated_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This is the connector configuration that was also passed to
	// Configure, therefore it's already validated.
	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Destination_Lifecycle_OnCreated_Request) Reset() {
	*x = Destination_Lifecycle_OnCreated_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle_OnCreated_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle_OnCreated_Request) ProtoMessage() {}

func (x *Destination_Lifecycle_OnCreated_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle_OnCreated_Request.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle_OnCreated_Request) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5, 0, 0}
}

func (x *Destination_Lifecycle_OnCreated_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Destination_Lifecycle_OnCreated_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Lifecycle_OnCreated_Response) Reset() {
	*x = Destination_Lifecycle_OnCreated_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle_OnCreated_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle_OnCreated_Response) ProtoMessage() {}

func (x *Destination_Lifecycle_OnCreated_Response) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle_OnCreated_Response.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle_OnCreated_Response) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5, 0, 1}
}

type Destination_Lifecycle_OnUpdated_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This is the old connector configuration that was used the last time
	// the connector was running. It was valid at that time, since it passed
	// through the Configure function.
	ConfigBefore map[string]string `protobuf:"bytes,1,rep,name=config_before,json=configBefore,proto3" json:"config_before,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// This is the new connector configuration that was also passed to
	// Configure, therefore it's already validated.
	ConfigAfter map[string]string `protobuf:"bytes,2,rep,name=config_after,json=configAfter,proto3" json:"config_after,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Destination_Lifecycle_OnUpdated_Request) Reset() {
	*x = Destination_Lifecycle_OnUpdated_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle_OnUpdated_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle_OnUpdated_Request) ProtoMessage() {}

func (x *Destination_Lifecycle_OnUpdated_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle_OnUpdated_Request.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle_OnUpdated_Request) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5, 1, 0}
}

func (x *Destination_Lifecycle_OnUpdated_Request) GetConfigBefore() map[string]string {
	if x != nil {
		return x.ConfigBefore
	}
	return nil
}

func (x *Destination_Lifecycle_OnUpdated_Request) GetConfigAfter() map[string]string {
	if x != nil {
		return x.ConfigAfter
	}
	return nil
}

type Destination_Lifecycle_OnUpdated_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Lifecycle_OnUpdated_Response) Reset() {
	*x = Destination_Lifecycle_OnUpdated_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle_OnUpdated_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle_OnUpdated_Response) ProtoMessage() {}

func (x *Destination_Lifecycle_OnUpdated_Response) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle_OnUpdated_Response.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle_OnUpdated_Response) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5, 1, 1}
}

type Destination_Lifecycle_OnDeleted_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This is the old connector configuration that was used the last time
	// the connector was running. It was valid at that time, since it passed
	// through the Configure function.
	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Destination_Lifecycle_OnDeleted_Request) Reset() {
	*x = Destination_Lifecycle_OnDeleted_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle_OnDeleted_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle_OnDeleted_Request) ProtoMessage() {}

func (x *Destination_Lifecycle_OnDeleted_Request) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle_OnDeleted_Request.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle_OnDeleted_Request) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5, 2, 0}
}

func (x *Destination_Lifecycle_OnDeleted_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Destination_Lifecycle_OnDeleted_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Destination_Lifecycle_OnDeleted_Response) Reset() {
	*x = Destination_Lifecycle_OnDeleted_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_connector_v2_destination_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Destination_Lifecycle_OnDeleted_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Destination_Lifecycle_OnDeleted_Response) ProtoMessage() {}

func (x *Destination_Lifecycle_OnDeleted_Response) ProtoReflect() protoreflect.Message {
	mi := &file_connector_v2_destination_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Destination_Lifecycle_OnDeleted_Response.ProtoReflect.Descriptor instead.
func (*Destination_Lifecycle_OnDeleted_Response) Descriptor() ([]byte, []int) {
	return file_connector_v2_destination_proto_rawDescGZIP(), []int{0, 5, 2, 1}
}

var File_connector_v2_destination_proto protoreflect.FileDescriptor

var file_connector_v2_destination_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x32, 0x2f, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x1a, 0x20,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x18, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x64, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x65,
	0x6e, 0x63, 0x64, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x0a, 0x0a, 0x0b, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0xaf, 0x01, 0x0a, 0x09, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x1a, 0x95, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x1d, 0x0a, 0x04,
	0x4f, 0x70, 0x65, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0xc4, 0x01, 0x0a, 0x03,
	0x52, 0x75, 0x6e, 0x1a, 0x37, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x64, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x07, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x1a, 0x83, 0x01, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x61, 0x63, 0x6b,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x41, 0x63, 0x6b, 0x52, 0x04, 0x61, 0x63, 0x6b, 0x73, 0x1a, 0x37, 0x0a, 0x03, 0x41, 0x63, 0x6b,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x1a, 0x42, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x1a, 0x2e, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6c, 0x61,
	0x73, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x21, 0x0a, 0x08, 0x54, 0x65, 0x61, 0x72, 0x64, 0x6f,
	0x77, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0a, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x83, 0x06, 0x0a, 0x09, 0x4c, 0x69,
	0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x1a, 0xb9, 0x01, 0x0a, 0x09, 0x4f, 0x6e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x9f, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x59, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x41, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32,
	0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x4f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x39, 0x0a, 0x0b,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0xfd, 0x02, 0x0a, 0x09, 0x4f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x1a, 0xe3, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x6c, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x62, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x47, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x4f, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x12, 0x69, 0x0a, 0x0c, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x46, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32,
	0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x4f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x41,
	0x66, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x41, 0x66, 0x74, 0x65, 0x72, 0x1a, 0x3f, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x42, 0x65, 0x66, 0x6f, 0x72, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3e, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x41, 0x66, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0xb9, 0x01, 0x0a, 0x09, 0x4f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x1a, 0x9f, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x59, 0x0a,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x41, 0x2e,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x2e, 0x4f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xfe, 0x06, 0x0a, 0x11, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x66, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x12, 0x2b, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76,
	0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2c, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a,
	0x04, 0x4f, 0x70, 0x65, 0x6e, 0x12, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x58, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x25, 0x2e,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x57, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x26, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e,
	0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x70,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x08, 0x54, 0x65, 0x61,
	0x72, 0x64, 0x6f, 0x77, 0x6e, 0x12, 0x2a, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x54, 0x65, 0x61, 0x72, 0x64, 0x6f, 0x77, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32,
	0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x65, 0x61,
	0x72, 0x64, 0x6f, 0x77, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x83,
	0x01, 0x0a, 0x12, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x4f, 0x6e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x35, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x4f, 0x6e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c,
	0x65, 0x2e, 0x4f, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x83, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x4f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x35, 0x2e, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65,
	0x2e, 0x4f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x36, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76,
	0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69,
	0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x4f, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x83, 0x01, 0x0a, 0x12, 0x4c,
	0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x4f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x12, 0x35, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32,
	0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x4f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x32, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e, 0x4f, 0x6e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0xc5, 0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x76, 0x32, 0x42, 0x10, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x69, 0x74, 0x69, 0x6f, 0x2f,
	0x63, 0x6f, 0x6e, 0x64, 0x75, 0x69, 0x74, 0x2d, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2f, 0x76, 0x32, 0x3b, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x76, 0x32, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa,
	0x02, 0x0c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x56, 0x32, 0xca, 0x02,
	0x0c, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5c, 0x56, 0x32, 0xe2, 0x02, 0x18,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x5c, 0x56, 0x32, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0d, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x3a, 0x3a, 0x56, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_connector_v2_destination_proto_rawDescOnce sync.Once
	file_connector_v2_destination_proto_rawDescData = file_connector_v2_destination_proto_rawDesc
)

func file_connector_v2_destination_proto_rawDescGZIP() []byte {
	file_connector_v2_destination_proto_rawDescOnce.Do(func() {
		file_connector_v2_destination_proto_rawDescData = protoimpl.X.CompressGZIP(file_connector_v2_destination_proto_rawDescData)
	})
	return file_connector_v2_destination_proto_rawDescData
}

var file_connector_v2_destination_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_connector_v2_destination_proto_goTypes = []interface{}{
	(*Destination)(nil),                              // 0: connector.v2.Destination
	(*Destination_Configure)(nil),                    // 1: connector.v2.Destination.Configure
	(*Destination_Open)(nil),                         // 2: connector.v2.Destination.Open
	(*Destination_Run)(nil),                          // 3: connector.v2.Destination.Run
	(*Destination_Stop)(nil),                         // 4: connector.v2.Destination.Stop
	(*Destination_Teardown)(nil),                     // 5: connector.v2.Destination.Teardown
	(*Destination_Lifecycle)(nil),                    // 6: connector.v2.Destination.Lifecycle
	(*Destination_Configure_Request)(nil),            // 7: connector.v2.Destination.Configure.Request
	(*Destination_Configure_Response)(nil),           // 8: connector.v2.Destination.Configure.Response
	nil,                                              // 9: connector.v2.Destination.Configure.Request.ConfigEntry
	(*Destination_Open_Request)(nil),                 // 10: connector.v2.Destination.Open.Request
	(*Destination_Open_Response)(nil),                // 11: connector.v2.Destination.Open.Response
	(*Destination_Run_Request)(nil),                  // 12: connector.v2.Destination.Run.Request
	(*Destination_Run_Response)(nil),                 // 13: connector.v2.Destination.Run.Response
	(*Destination_Run_Response_Ack)(nil),             // 14: connector.v2.Destination.Run.Response.Ack
	(*Destination_Stop_Request)(nil),                 // 15: connector.v2.Destination.Stop.Request
	(*Destination_Stop_Response)(nil),                // 16: connector.v2.Destination.Stop.Response
	(*Destination_Teardown_Request)(nil),             // 17: connector.v2.Destination.Teardown.Request
	(*Destination_Teardown_Response)(nil),            // 18: connector.v2.Destination.Teardown.Response
	(*Destination_Lifecycle_OnCreated)(nil),          // 19: connector.v2.Destination.Lifecycle.OnCreated
	(*Destination_Lifecycle_OnUpdated)(nil),          // 20: connector.v2.Destination.Lifecycle.OnUpdated
	(*Destination_Lifecycle_OnDeleted)(nil),          // 21: connector.v2.Destination.Lifecycle.OnDeleted
	(*Destination_Lifecycle_OnCreated_Request)(nil),  // 22: connector.v2.Destination.Lifecycle.OnCreated.Request
	(*Destination_Lifecycle_OnCreated_Response)(nil), // 23: connector.v2.Destination.Lifecycle.OnCreated.Response
	nil, // 24: connector.v2.Destination.Lifecycle.OnCreated.Request.ConfigEntry
	(*Destination_Lifecycle_OnUpdated_Request)(nil),  // 25: connector.v2.Destination.Lifecycle.OnUpdated.Request
	(*Destination_Lifecycle_OnUpdated_Response)(nil), // 26: connector.v2.Destination.Lifecycle.OnUpdated.Response
	nil, // 27: connector.v2.Destination.Lifecycle.OnUpdated.Request.ConfigBeforeEntry
	nil, // 28: connector.v2.Destination.Lifecycle.OnUpdated.Request.ConfigAfterEntry
	(*Destination_Lifecycle_OnDeleted_Request)(nil),  // 29: connector.v2.Destination.Lifecycle.OnDeleted.Request
	(*Destination_Lifecycle_OnDeleted_Response)(nil), // 30: connector.v2.Destination.Lifecycle.OnDeleted.Response
	nil,               // 31: connector.v2.Destination.Lifecycle.OnDeleted.Request.ConfigEntry
	(*v1.Record)(nil), // 32: opencdc.v1.Record
}
var file_connector_v2_destination_proto_depIdxs = []int32{
	9,  // 0: connector.v2.Destination.Configure.Request.config:type_name -> connector.v2.Destination.Configure.Request.ConfigEntry
	32, // 1: connector.v2.Destination.Run.Request.records:type_name -> opencdc.v1.Record
	14, // 2: connector.v2.Destination.Run.Response.acks:type_name -> connector.v2.Destination.Run.Response.Ack
	24, // 3: connector.v2.Destination.Lifecycle.OnCreated.Request.config:type_name -> connector.v2.Destination.Lifecycle.OnCreated.Request.ConfigEntry
	27, // 4: connector.v2.Destination.Lifecycle.OnUpdated.Request.config_before:type_name -> connector.v2.Destination.Lifecycle.OnUpdated.Request.ConfigBeforeEntry
	28, // 5: connector.v2.Destination.Lifecycle.OnUpdated.Request.config_after:type_name -> connector.v2.Destination.Lifecycle.OnUpdated.Request.ConfigAfterEntry
	31, // 6: connector.v2.Destination.Lifecycle.OnDeleted.Request.config:type_name -> connector.v2.Destination.Lifecycle.OnDeleted.Request.ConfigEntry
	7,  // 7: connector.v2.DestinationPlugin.Configure:input_type -> connector.v2.Destination.Configure.Request
	10, // 8: connector.v2.DestinationPlugin.Open:input_type -> connector.v2.Destination.Open.Request
	12, // 9: connector.v2.DestinationPlugin.Run:input_type -> connector.v2.Destination.Run.Request
	15, // 10: connector.v2.DestinationPlugin.Stop:input_type -> connector.v2.Destination.Stop.Request
	17, // 11: connector.v2.DestinationPlugin.Teardown:input_type -> connector.v2.Destination.Teardown.Request
	22, // 12: connector.v2.DestinationPlugin.LifecycleOnCreated:input_type -> connector.v2.Destination.Lifecycle.OnCreated.Request
	25, // 13: connector.v2.DestinationPlugin.LifecycleOnUpdated:input_type -> connector.v2.Destination.Lifecycle.OnUpdated.Request
	29, // 14: connector.v2.DestinationPlugin.LifecycleOnDeleted:input_type -> connector.v2.Destination.Lifecycle.OnDeleted.Request
	8,  // 15: connector.v2.DestinationPlugin.Configure:output_type -> connector.v2.Destination.Configure.Response
	11, // 16: connector.v2.DestinationPlugin.Open:output_type -> connector.v2.Destination.Open.Response
	13, // 17: connector.v2.DestinationPlugin.Run:output_type -> connector.v2.Destination.Run.Response
	16, // 18: connector.v2.DestinationPlugin.Stop:output_type -> connector.v2.Destination.Stop.Response
	18, // 19: connector.v2.DestinationPlugin.Teardown:output_type -> connector.v2.Destination.Teardown.Response
	23, // 20: connector.v2.DestinationPlugin.LifecycleOnCreated:output_type -> connector.v2.Destination.Lifecycle.OnCreated.Response
	26, // 21: connector.v2.DestinationPlugin.LifecycleOnUpdated:output_type -> connector.v2.Destination.Lifecycle.OnUpdated.Response
	30, // 22: connector.v2.DestinationPlugin.LifecycleOnDeleted:output_type -> connector.v2.Destination.Lifecycle.OnDeleted.Response
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_connector_v2_destination_proto_init() }
func file_connector_v2_destination_proto_init() {
	if File_connector_v2_destination_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_connector_v2_destination_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Configure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Open); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Run); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Teardown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Configure_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Configure_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Open_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Open_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Run_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Run_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Run_Response_Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Stop_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Stop_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Teardown_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Teardown_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle_OnCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle_OnUpdated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle_OnDeleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle_OnCreated_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle_OnCreated_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle_OnUpdated_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle_OnUpdated_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle_OnDeleted_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_connector_v2_destination_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Destination_Lifecycle_OnDeleted_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_connector_v2_destination_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_connector_v2_destination_proto_goTypes,
		DependencyIndexes: file_connector_v2_destination_proto_depIdxs,
		MessageInfos:      file_connector_v2_destination_proto_msgTypes,
	}.Build()
	File_connector_v2_destination_proto = out.File
	file_connector_v2_destination_proto_rawDesc = nil
	file_connector_v2_destination_proto_goTypes = nil
	file_connector_v2_destination_proto_depIdxs = nil
}
