// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: schema_service/v1/schema_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SchemaType int32

const (
	SchemaType_TYPE_UNDEFINED SchemaType = 0
	SchemaType_TYPE_AVRO      SchemaType = 1
)

// Enum value maps for SchemaType.
var (
	SchemaType_name = map[int32]string{
		0: "TYPE_UNDEFINED",
		1: "TYPE_AVRO",
	}
	SchemaType_value = map[string]int32{
		"TYPE_UNDEFINED": 0,
		"TYPE_AVRO":      1,
	}
)

func (x SchemaType) Enum() *SchemaType {
	p := new(SchemaType)
	*p = x
	return p
}

func (x SchemaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchemaType) Descriptor() protoreflect.EnumDescriptor {
	return file_schema_service_v1_schema_service_proto_enumTypes[0].Descriptor()
}

func (SchemaType) Type() protoreflect.EnumType {
	return &file_schema_service_v1_schema_service_proto_enumTypes[0]
}

func (x SchemaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchemaType.Descriptor instead.
func (SchemaType) EnumDescriptor() ([]byte, []int) {
	return file_schema_service_v1_schema_service_proto_rawDescGZIP(), []int{0}
}

type RegisterSchemaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version int32      `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Type    SchemaType `protobuf:"varint,3,opt,name=type,proto3,enum=SchemaType" json:"type,omitempty"`
	Bytes   []byte     `protobuf:"bytes,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *RegisterSchemaRequest) Reset() {
	*x = RegisterSchemaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_service_v1_schema_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaRequest) ProtoMessage() {}

func (x *RegisterSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_service_v1_schema_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaRequest.ProtoReflect.Descriptor instead.
func (*RegisterSchemaRequest) Descriptor() ([]byte, []int) {
	return file_schema_service_v1_schema_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSchemaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterSchemaRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RegisterSchemaRequest) GetType() SchemaType {
	if x != nil {
		return x.Type
	}
	return SchemaType_TYPE_UNDEFINED
}

func (x *RegisterSchemaRequest) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type RegisterSchemaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegisterSchemaResponse) Reset() {
	*x = RegisterSchemaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_service_v1_schema_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSchemaResponse) ProtoMessage() {}

func (x *RegisterSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_service_v1_schema_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSchemaResponse.ProtoReflect.Descriptor instead.
func (*RegisterSchemaResponse) Descriptor() ([]byte, []int) {
	return file_schema_service_v1_schema_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterSchemaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FetchSchemaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FetchSchemaRequest) Reset() {
	*x = FetchSchemaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_service_v1_schema_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchSchemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSchemaRequest) ProtoMessage() {}

func (x *FetchSchemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_schema_service_v1_schema_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSchemaRequest.ProtoReflect.Descriptor instead.
func (*FetchSchemaRequest) Descriptor() ([]byte, []int) {
	return file_schema_service_v1_schema_service_proto_rawDescGZIP(), []int{2}
}

func (x *FetchSchemaRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FetchSchemaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version int32      `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Type    SchemaType `protobuf:"varint,4,opt,name=type,proto3,enum=SchemaType" json:"type,omitempty"`
	Bytes   []byte     `protobuf:"bytes,5,opt,name=bytes,proto3" json:"bytes,omitempty"`
}

func (x *FetchSchemaResponse) Reset() {
	*x = FetchSchemaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_service_v1_schema_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchSchemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSchemaResponse) ProtoMessage() {}

func (x *FetchSchemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_service_v1_schema_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSchemaResponse.ProtoReflect.Descriptor instead.
func (*FetchSchemaResponse) Descriptor() ([]byte, []int) {
	return file_schema_service_v1_schema_service_proto_rawDescGZIP(), []int{3}
}

func (x *FetchSchemaResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FetchSchemaResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FetchSchemaResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FetchSchemaResponse) GetType() SchemaType {
	if x != nil {
		return x.Type
	}
	return SchemaType_TYPE_UNDEFINED
}

func (x *FetchSchemaResponse) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

var File_schema_service_v1_schema_service_proto protoreflect.FileDescriptor

var file_schema_service_v1_schema_service_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7c, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x1f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x22, 0x28, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x24, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x8a, 0x01, 0x0a, 0x13, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x2a, 0x2f, 0x0a, 0x0a, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49,
	0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x56,
	0x52, 0x4f, 0x10, 0x01, 0x32, 0x80, 0x01, 0x0a, 0x0d, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x16, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x46, 0x65, 0x74, 0x63, 0x68, 0x12, 0x13, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x5f, 0x42, 0x12, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x47, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x64,
	0x75, 0x69, 0x74, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x69, 0x74, 0x2d, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_service_v1_schema_service_proto_rawDescOnce sync.Once
	file_schema_service_v1_schema_service_proto_rawDescData = file_schema_service_v1_schema_service_proto_rawDesc
)

func file_schema_service_v1_schema_service_proto_rawDescGZIP() []byte {
	file_schema_service_v1_schema_service_proto_rawDescOnce.Do(func() {
		file_schema_service_v1_schema_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_service_v1_schema_service_proto_rawDescData)
	})
	return file_schema_service_v1_schema_service_proto_rawDescData
}

var file_schema_service_v1_schema_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schema_service_v1_schema_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_schema_service_v1_schema_service_proto_goTypes = []interface{}{
	(SchemaType)(0),                // 0: SchemaType
	(*RegisterSchemaRequest)(nil),  // 1: RegisterSchemaRequest
	(*RegisterSchemaResponse)(nil), // 2: RegisterSchemaResponse
	(*FetchSchemaRequest)(nil),     // 3: FetchSchemaRequest
	(*FetchSchemaResponse)(nil),    // 4: FetchSchemaResponse
}
var file_schema_service_v1_schema_service_proto_depIdxs = []int32{
	0, // 0: RegisterSchemaRequest.type:type_name -> SchemaType
	0, // 1: FetchSchemaResponse.type:type_name -> SchemaType
	1, // 2: SchemaService.Register:input_type -> RegisterSchemaRequest
	3, // 3: SchemaService.Fetch:input_type -> FetchSchemaRequest
	2, // 4: SchemaService.Register:output_type -> RegisterSchemaResponse
	4, // 5: SchemaService.Fetch:output_type -> FetchSchemaResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_schema_service_v1_schema_service_proto_init() }
func file_schema_service_v1_schema_service_proto_init() {
	if File_schema_service_v1_schema_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_service_v1_schema_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterSchemaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_service_v1_schema_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterSchemaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_service_v1_schema_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchSchemaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_service_v1_schema_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchSchemaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_service_v1_schema_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_schema_service_v1_schema_service_proto_goTypes,
		DependencyIndexes: file_schema_service_v1_schema_service_proto_depIdxs,
		EnumInfos:         file_schema_service_v1_schema_service_proto_enumTypes,
		MessageInfos:      file_schema_service_v1_schema_service_proto_msgTypes,
	}.Build()
	File_schema_service_v1_schema_service_proto = out.File
	file_schema_service_v1_schema_service_proto_rawDesc = nil
	file_schema_service_v1_schema_service_proto_goTypes = nil
	file_schema_service_v1_schema_service_proto_depIdxs = nil
}
