// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: cproto.proto

package cproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Record struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position  []byte                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Metadata  map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Key       *Data                  `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Payload   *Data                  `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Record) Reset() {
	*x = Record{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetPosition() []byte {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Record) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Record) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Record) GetKey() *Data {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Record) GetPayload() *Data {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*Data_RawData
	//	*Data_StructuredData
	Data isData_Data `protobuf_oneof:"data"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{1}
}

func (m *Data) GetData() isData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Data) GetRawData() []byte {
	if x, ok := x.GetData().(*Data_RawData); ok {
		return x.RawData
	}
	return nil
}

func (x *Data) GetStructuredData() *structpb.Struct {
	if x, ok := x.GetData().(*Data_StructuredData); ok {
		return x.StructuredData
	}
	return nil
}

type isData_Data interface {
	isData_Data()
}

type Data_RawData struct {
	RawData []byte `protobuf:"bytes,1,opt,name=rawData,proto3,oneof"`
}

type Data_StructuredData struct {
	StructuredData *structpb.Struct `protobuf:"bytes,2,opt,name=structuredData,proto3,oneof"`
}

func (*Data_RawData) isData_Data() {}

func (*Data_StructuredData) isData_Data() {}

type Source struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source) Reset() {
	*x = Source{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2}
}

type Sink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink) Reset() {
	*x = Sink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink) ProtoMessage() {}

func (x *Sink) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink.ProtoReflect.Descriptor instead.
func (*Sink) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3}
}

type Specifier struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Specifier) Reset() {
	*x = Specifier{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specifier) ProtoMessage() {}

func (x *Specifier) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specifier.ProtoReflect.Descriptor instead.
func (*Specifier) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{4}
}

type Source_Configure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source_Configure) Reset() {
	*x = Source_Configure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Configure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Configure) ProtoMessage() {}

func (x *Source_Configure) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Configure.ProtoReflect.Descriptor instead.
func (*Source_Configure) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 0}
}

type Source_Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source_Start) Reset() {
	*x = Source_Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Start) ProtoMessage() {}

func (x *Source_Start) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Start.ProtoReflect.Descriptor instead.
func (*Source_Start) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 1}
}

type Source_Run struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source_Run) Reset() {
	*x = Source_Run{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Run) ProtoMessage() {}

func (x *Source_Run) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Run.ProtoReflect.Descriptor instead.
func (*Source_Run) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 2}
}

type Source_Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source_Stop) Reset() {
	*x = Source_Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Stop) ProtoMessage() {}

func (x *Source_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Stop.ProtoReflect.Descriptor instead.
func (*Source_Stop) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 3}
}

type Source_Configure_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Source_Configure_Request) Reset() {
	*x = Source_Configure_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Configure_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Configure_Request) ProtoMessage() {}

func (x *Source_Configure_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Configure_Request.ProtoReflect.Descriptor instead.
func (*Source_Configure_Request) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *Source_Configure_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Source_Configure_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source_Configure_Response) Reset() {
	*x = Source_Configure_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Configure_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Configure_Response) ProtoMessage() {}

func (x *Source_Configure_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Configure_Response.ProtoReflect.Descriptor instead.
func (*Source_Configure_Response) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 0, 1}
}

type Source_Start_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position []byte `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
}

func (x *Source_Start_Request) Reset() {
	*x = Source_Start_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Start_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Start_Request) ProtoMessage() {}

func (x *Source_Start_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Start_Request.ProtoReflect.Descriptor instead.
func (*Source_Start_Request) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 1, 0}
}

func (x *Source_Start_Request) GetPosition() []byte {
	if x != nil {
		return x.Position
	}
	return nil
}

type Source_Start_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source_Start_Response) Reset() {
	*x = Source_Start_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Start_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Start_Response) ProtoMessage() {}

func (x *Source_Start_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Start_Response.ProtoReflect.Descriptor instead.
func (*Source_Start_Response) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 1, 1}
}

type Source_Run_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AckPosition []byte `protobuf:"bytes,1,opt,name=ackPosition,proto3" json:"ackPosition,omitempty"`
}

func (x *Source_Run_Request) Reset() {
	*x = Source_Run_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Run_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Run_Request) ProtoMessage() {}

func (x *Source_Run_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Run_Request.ProtoReflect.Descriptor instead.
func (*Source_Run_Request) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 2, 0}
}

func (x *Source_Run_Request) GetAckPosition() []byte {
	if x != nil {
		return x.AckPosition
	}
	return nil
}

type Source_Run_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *Source_Run_Response) Reset() {
	*x = Source_Run_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Run_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Run_Response) ProtoMessage() {}

func (x *Source_Run_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Run_Response.ProtoReflect.Descriptor instead.
func (*Source_Run_Response) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 2, 1}
}

func (x *Source_Run_Response) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type Source_Stop_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source_Stop_Request) Reset() {
	*x = Source_Stop_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Stop_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Stop_Request) ProtoMessage() {}

func (x *Source_Stop_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Stop_Request.ProtoReflect.Descriptor instead.
func (*Source_Stop_Request) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 3, 0}
}

type Source_Stop_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Source_Stop_Response) Reset() {
	*x = Source_Stop_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Source_Stop_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source_Stop_Response) ProtoMessage() {}

func (x *Source_Stop_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source_Stop_Response.ProtoReflect.Descriptor instead.
func (*Source_Stop_Response) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{2, 3, 1}
}

type Sink_Configure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink_Configure) Reset() {
	*x = Sink_Configure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Configure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Configure) ProtoMessage() {}

func (x *Sink_Configure) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Configure.ProtoReflect.Descriptor instead.
func (*Sink_Configure) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 0}
}

type Sink_Start struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink_Start) Reset() {
	*x = Sink_Start{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Start) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Start) ProtoMessage() {}

func (x *Sink_Start) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Start.ProtoReflect.Descriptor instead.
func (*Sink_Start) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 1}
}

type Sink_Run struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink_Run) Reset() {
	*x = Sink_Run{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Run) ProtoMessage() {}

func (x *Sink_Run) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Run.ProtoReflect.Descriptor instead.
func (*Sink_Run) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 2}
}

type Sink_Stop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink_Stop) Reset() {
	*x = Sink_Stop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Stop) ProtoMessage() {}

func (x *Sink_Stop) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Stop.ProtoReflect.Descriptor instead.
func (*Sink_Stop) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 3}
}

type Sink_Configure_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config map[string]string `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Sink_Configure_Request) Reset() {
	*x = Sink_Configure_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Configure_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Configure_Request) ProtoMessage() {}

func (x *Sink_Configure_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Configure_Request.ProtoReflect.Descriptor instead.
func (*Sink_Configure_Request) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 0, 0}
}

func (x *Sink_Configure_Request) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type Sink_Configure_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink_Configure_Response) Reset() {
	*x = Sink_Configure_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Configure_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Configure_Response) ProtoMessage() {}

func (x *Sink_Configure_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Configure_Response.ProtoReflect.Descriptor instead.
func (*Sink_Configure_Response) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 0, 1}
}

type Sink_Start_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink_Start_Request) Reset() {
	*x = Sink_Start_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Start_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Start_Request) ProtoMessage() {}

func (x *Sink_Start_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Start_Request.ProtoReflect.Descriptor instead.
func (*Sink_Start_Request) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 1, 0}
}

type Sink_Start_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink_Start_Response) Reset() {
	*x = Sink_Start_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Start_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Start_Response) ProtoMessage() {}

func (x *Sink_Start_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Start_Response.ProtoReflect.Descriptor instead.
func (*Sink_Start_Response) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 1, 1}
}

type Sink_Run_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *Sink_Run_Request) Reset() {
	*x = Sink_Run_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Run_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Run_Request) ProtoMessage() {}

func (x *Sink_Run_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Run_Request.ProtoReflect.Descriptor instead.
func (*Sink_Run_Request) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 2, 0}
}

func (x *Sink_Run_Request) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type Sink_Run_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AckPosition []byte `protobuf:"bytes,1,opt,name=ackPosition,proto3" json:"ackPosition,omitempty"`
	Error       string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Sink_Run_Response) Reset() {
	*x = Sink_Run_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Run_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Run_Response) ProtoMessage() {}

func (x *Sink_Run_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Run_Response.ProtoReflect.Descriptor instead.
func (*Sink_Run_Response) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 2, 1}
}

func (x *Sink_Run_Response) GetAckPosition() []byte {
	if x != nil {
		return x.AckPosition
	}
	return nil
}

func (x *Sink_Run_Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Sink_Stop_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink_Stop_Request) Reset() {
	*x = Sink_Stop_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Stop_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Stop_Request) ProtoMessage() {}

func (x *Sink_Stop_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Stop_Request.ProtoReflect.Descriptor instead.
func (*Sink_Stop_Request) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 3, 0}
}

type Sink_Stop_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sink_Stop_Response) Reset() {
	*x = Sink_Stop_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sink_Stop_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sink_Stop_Response) ProtoMessage() {}

func (x *Sink_Stop_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sink_Stop_Response.ProtoReflect.Descriptor instead.
func (*Sink_Stop_Response) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{3, 3, 1}
}

type Specifier_Specify struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Specifier_Specify) Reset() {
	*x = Specifier_Specify{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specifier_Specify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specifier_Specify) ProtoMessage() {}

func (x *Specifier_Specify) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specifier_Specify.ProtoReflect.Descriptor instead.
func (*Specifier_Specify) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{4, 0}
}

type Specifier_Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default     string `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Required    bool   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Specifier_Parameter) Reset() {
	*x = Specifier_Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specifier_Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specifier_Parameter) ProtoMessage() {}

func (x *Specifier_Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specifier_Parameter.ProtoReflect.Descriptor instead.
func (*Specifier_Parameter) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Specifier_Parameter) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *Specifier_Parameter) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *Specifier_Parameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Specifier_Specify_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Specifier_Specify_Request) Reset() {
	*x = Specifier_Specify_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specifier_Specify_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specifier_Specify_Request) ProtoMessage() {}

func (x *Specifier_Specify_Request) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specifier_Specify_Request.ProtoReflect.Descriptor instead.
func (*Specifier_Specify_Request) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{4, 0, 0}
}

type Specifier_Specify_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summary     string                          `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Description string                          `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Version     string                          `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Author      string                          `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	SinkSpec    map[string]*Specifier_Parameter `protobuf:"bytes,5,rep,name=sinkSpec,proto3" json:"sinkSpec,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	SourceSpec  map[string]*Specifier_Parameter `protobuf:"bytes,6,rep,name=sourceSpec,proto3" json:"sourceSpec,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Specifier_Specify_Response) Reset() {
	*x = Specifier_Specify_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cproto_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Specifier_Specify_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specifier_Specify_Response) ProtoMessage() {}

func (x *Specifier_Specify_Response) ProtoReflect() protoreflect.Message {
	mi := &file_cproto_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specifier_Specify_Response.ProtoReflect.Descriptor instead.
func (*Specifier_Specify_Response) Descriptor() ([]byte, []int) {
	return file_cproto_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *Specifier_Specify_Response) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Specifier_Specify_Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Specifier_Specify_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Specifier_Specify_Response) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Specifier_Specify_Response) GetSinkSpec() map[string]*Specifier_Parameter {
	if x != nil {
		return x.SinkSpec
	}
	return nil
}

func (x *Specifier_Specify_Response) GetSourceSpec() map[string]*Specifier_Parameter {
	if x != nil {
		return x.SourceSpec
	}
	return nil
}

var File_cproto_proto protoreflect.FileDescriptor

var file_cproto_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa6, 0x02, 0x0a, 0x06, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x3b, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x38,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x21, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76,
	0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63,
	0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x6d, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1a, 0x0a, 0x07, 0x72,
	0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x07,
	0x72, 0x61, 0x77, 0x44, 0x61, 0x74, 0x61, 0x12, 0x41, 0x0a, 0x0e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0xf8, 0x02, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x1a, 0xa7, 0x01,
	0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x1a, 0x8d, 0x01, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x47, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x0a, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x3a, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x1a, 0x25, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x1a, 0x69, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x1a, 0x2b, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x6b, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63, 0x6b, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x35, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x1d,
	0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xee, 0x02,
	0x0a, 0x04, 0x53, 0x69, 0x6e, 0x6b, 0x1a, 0xa5, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x1a, 0x8b, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x45, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x2d, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e,
	0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x39, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x1e,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x7f,
	0x0a, 0x03, 0x52, 0x75, 0x6e, 0x1a, 0x34, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x29, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x1a, 0x42, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x6b, 0x50, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x61, 0x63,
	0x6b, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a,
	0x1d, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xe6,
	0x04, 0x0a, 0x09, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x1a, 0xf3, 0x03, 0x0a,
	0x07, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0xdc, 0x03, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x4f,
	0x0a, 0x08, 0x73, 0x69, 0x6e, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x33, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x53, 0x70, 0x65, 0x63,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x73, 0x69, 0x6e, 0x6b, 0x53, 0x70, 0x65, 0x63, 0x12,
	0x55, 0x0a, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x53, 0x70, 0x65, 0x63, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x1a, 0x5b, 0x0a, 0x0d, 0x53, 0x69, 0x6e, 0x6b, 0x53, 0x70,
	0x65, 0x63, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x5d, 0x0a, 0x0f, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x70, 0x65,
	0x63, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x1a, 0x63, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xc5, 0x02, 0x0a, 0x0c, 0x53, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x56, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x23, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76,
	0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x4a, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1f, 0x2e, 0x63, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x63, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x03,
	0x52, 0x75, 0x6e, 0x12, 0x1d, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e,
	0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x12, 0x47, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x1e,
	0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0xb3, 0x02, 0x0a, 0x0a, 0x53, 0x69, 0x6e, 0x6b, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x52,
	0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x21, 0x2e, 0x63, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x2e,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x46, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1d, 0x2e, 0x63, 0x70,
	0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x70, 0x6c,
	0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x03, 0x52, 0x75,
	0x6e, 0x12, 0x1b, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x6e, 0x6b, 0x2e, 0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x2e,
	0x52, 0x75, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x43, 0x0a, 0x04, 0x53, 0x74, 0x6f, 0x70, 0x12, 0x1c, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67,
	0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x76, 0x31, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x69, 0x0a, 0x0f, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x12, 0x56, 0x0a, 0x07, 0x53, 0x70, 0x65, 0x63,
	0x69, 0x66, 0x79, 0x12, 0x24, 0x2e, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x79, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x63, 0x70, 0x6c, 0x75,
	0x67, 0x69, 0x6e, 0x76, 0x31, 0x2e, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x6f, 0x6e, 0x64, 0x75, 0x69, 0x74, 0x69, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x64, 0x75, 0x69, 0x74,
	0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x63, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x76,
	0x31, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cproto_proto_rawDescOnce sync.Once
	file_cproto_proto_rawDescData = file_cproto_proto_rawDesc
)

func file_cproto_proto_rawDescGZIP() []byte {
	file_cproto_proto_rawDescOnce.Do(func() {
		file_cproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_cproto_proto_rawDescData)
	})
	return file_cproto_proto_rawDescData
}

var file_cproto_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_cproto_proto_goTypes = []interface{}{
	(*Record)(nil),                     // 0: cpluginv1.Record
	(*Data)(nil),                       // 1: cpluginv1.Data
	(*Source)(nil),                     // 2: cpluginv1.Source
	(*Sink)(nil),                       // 3: cpluginv1.Sink
	(*Specifier)(nil),                  // 4: cpluginv1.Specifier
	nil,                                // 5: cpluginv1.Record.MetadataEntry
	(*Source_Configure)(nil),           // 6: cpluginv1.Source.Configure
	(*Source_Start)(nil),               // 7: cpluginv1.Source.Start
	(*Source_Run)(nil),                 // 8: cpluginv1.Source.Run
	(*Source_Stop)(nil),                // 9: cpluginv1.Source.Stop
	(*Source_Configure_Request)(nil),   // 10: cpluginv1.Source.Configure.Request
	(*Source_Configure_Response)(nil),  // 11: cpluginv1.Source.Configure.Response
	nil,                                // 12: cpluginv1.Source.Configure.Request.ConfigEntry
	(*Source_Start_Request)(nil),       // 13: cpluginv1.Source.Start.Request
	(*Source_Start_Response)(nil),      // 14: cpluginv1.Source.Start.Response
	(*Source_Run_Request)(nil),         // 15: cpluginv1.Source.Run.Request
	(*Source_Run_Response)(nil),        // 16: cpluginv1.Source.Run.Response
	(*Source_Stop_Request)(nil),        // 17: cpluginv1.Source.Stop.Request
	(*Source_Stop_Response)(nil),       // 18: cpluginv1.Source.Stop.Response
	(*Sink_Configure)(nil),             // 19: cpluginv1.Sink.Configure
	(*Sink_Start)(nil),                 // 20: cpluginv1.Sink.Start
	(*Sink_Run)(nil),                   // 21: cpluginv1.Sink.Run
	(*Sink_Stop)(nil),                  // 22: cpluginv1.Sink.Stop
	(*Sink_Configure_Request)(nil),     // 23: cpluginv1.Sink.Configure.Request
	(*Sink_Configure_Response)(nil),    // 24: cpluginv1.Sink.Configure.Response
	nil,                                // 25: cpluginv1.Sink.Configure.Request.ConfigEntry
	(*Sink_Start_Request)(nil),         // 26: cpluginv1.Sink.Start.Request
	(*Sink_Start_Response)(nil),        // 27: cpluginv1.Sink.Start.Response
	(*Sink_Run_Request)(nil),           // 28: cpluginv1.Sink.Run.Request
	(*Sink_Run_Response)(nil),          // 29: cpluginv1.Sink.Run.Response
	(*Sink_Stop_Request)(nil),          // 30: cpluginv1.Sink.Stop.Request
	(*Sink_Stop_Response)(nil),         // 31: cpluginv1.Sink.Stop.Response
	(*Specifier_Specify)(nil),          // 32: cpluginv1.Specifier.Specify
	(*Specifier_Parameter)(nil),        // 33: cpluginv1.Specifier.Parameter
	(*Specifier_Specify_Request)(nil),  // 34: cpluginv1.Specifier.Specify.Request
	(*Specifier_Specify_Response)(nil), // 35: cpluginv1.Specifier.Specify.Response
	nil,                                // 36: cpluginv1.Specifier.Specify.Response.SinkSpecEntry
	nil,                                // 37: cpluginv1.Specifier.Specify.Response.SourceSpecEntry
	(*timestamppb.Timestamp)(nil),      // 38: google.protobuf.Timestamp
	(*structpb.Struct)(nil),            // 39: google.protobuf.Struct
}
var file_cproto_proto_depIdxs = []int32{
	5,  // 0: cpluginv1.Record.metadata:type_name -> cpluginv1.Record.MetadataEntry
	38, // 1: cpluginv1.Record.createdAt:type_name -> google.protobuf.Timestamp
	1,  // 2: cpluginv1.Record.key:type_name -> cpluginv1.Data
	1,  // 3: cpluginv1.Record.payload:type_name -> cpluginv1.Data
	39, // 4: cpluginv1.Data.structuredData:type_name -> google.protobuf.Struct
	12, // 5: cpluginv1.Source.Configure.Request.config:type_name -> cpluginv1.Source.Configure.Request.ConfigEntry
	0,  // 6: cpluginv1.Source.Run.Response.record:type_name -> cpluginv1.Record
	25, // 7: cpluginv1.Sink.Configure.Request.config:type_name -> cpluginv1.Sink.Configure.Request.ConfigEntry
	0,  // 8: cpluginv1.Sink.Run.Request.record:type_name -> cpluginv1.Record
	36, // 9: cpluginv1.Specifier.Specify.Response.sinkSpec:type_name -> cpluginv1.Specifier.Specify.Response.SinkSpecEntry
	37, // 10: cpluginv1.Specifier.Specify.Response.sourceSpec:type_name -> cpluginv1.Specifier.Specify.Response.SourceSpecEntry
	33, // 11: cpluginv1.Specifier.Specify.Response.SinkSpecEntry.value:type_name -> cpluginv1.Specifier.Parameter
	33, // 12: cpluginv1.Specifier.Specify.Response.SourceSpecEntry.value:type_name -> cpluginv1.Specifier.Parameter
	10, // 13: cpluginv1.SourcePlugin.Configure:input_type -> cpluginv1.Source.Configure.Request
	13, // 14: cpluginv1.SourcePlugin.Start:input_type -> cpluginv1.Source.Start.Request
	15, // 15: cpluginv1.SourcePlugin.Run:input_type -> cpluginv1.Source.Run.Request
	17, // 16: cpluginv1.SourcePlugin.Stop:input_type -> cpluginv1.Source.Stop.Request
	23, // 17: cpluginv1.SinkPlugin.Configure:input_type -> cpluginv1.Sink.Configure.Request
	26, // 18: cpluginv1.SinkPlugin.Start:input_type -> cpluginv1.Sink.Start.Request
	28, // 19: cpluginv1.SinkPlugin.Run:input_type -> cpluginv1.Sink.Run.Request
	30, // 20: cpluginv1.SinkPlugin.Stop:input_type -> cpluginv1.Sink.Stop.Request
	34, // 21: cpluginv1.SpecifierPlugin.Specify:input_type -> cpluginv1.Specifier.Specify.Request
	11, // 22: cpluginv1.SourcePlugin.Configure:output_type -> cpluginv1.Source.Configure.Response
	14, // 23: cpluginv1.SourcePlugin.Start:output_type -> cpluginv1.Source.Start.Response
	16, // 24: cpluginv1.SourcePlugin.Run:output_type -> cpluginv1.Source.Run.Response
	18, // 25: cpluginv1.SourcePlugin.Stop:output_type -> cpluginv1.Source.Stop.Response
	24, // 26: cpluginv1.SinkPlugin.Configure:output_type -> cpluginv1.Sink.Configure.Response
	27, // 27: cpluginv1.SinkPlugin.Start:output_type -> cpluginv1.Sink.Start.Response
	29, // 28: cpluginv1.SinkPlugin.Run:output_type -> cpluginv1.Sink.Run.Response
	31, // 29: cpluginv1.SinkPlugin.Stop:output_type -> cpluginv1.Sink.Stop.Response
	35, // 30: cpluginv1.SpecifierPlugin.Specify:output_type -> cpluginv1.Specifier.Specify.Response
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cproto_proto_init() }
func file_cproto_proto_init() {
	if File_cproto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cproto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Record); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specifier); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Configure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Run); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Configure_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Configure_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Start_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Start_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Run_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Run_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Stop_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Source_Stop_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Configure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Start); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Run); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Stop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Configure_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Configure_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Start_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Start_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Run_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Run_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Stop_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sink_Stop_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specifier_Specify); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specifier_Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specifier_Specify_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cproto_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Specifier_Specify_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_cproto_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*Data_RawData)(nil),
		(*Data_StructuredData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cproto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_cproto_proto_goTypes,
		DependencyIndexes: file_cproto_proto_depIdxs,
		MessageInfos:      file_cproto_proto_msgTypes,
	}.Build()
	File_cproto_proto = out.File
	file_cproto_proto_rawDesc = nil
	file_cproto_proto_goTypes = nil
	file_cproto_proto_depIdxs = nil
}
